/* Static revision app. Content is public JSON; answers and papers exist in memory only. */
'use strict';
const app = document.getElementById('app');
const params = new URLSearchParams(location.search);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url = args => 'index.html?' + new URLSearchParams(args);
const button = (label, args) => `<a class="btn ghost" href="${esc(url(args))}">${esc(label)}</a>`;
const title = (eyebrow,heading,lead) => `<section class="hero"><p class="eyebrow">${esc(eyebrow)}</p><h1>${esc(heading)}</h1><p class="lead">${esc(lead)}</p></section>`;
const notice = text => text ? `<p class="notice">${esc(text)}</p>` : '';
const questionCount = unit => Object.values(unit.topics).reduce((n,t)=>n+t.questions.length,0);
const shuffle = values => { const a=values.slice(); for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];} return a; };
function balanced(pool,n) {
 const groups=new Map();shuffle(pool).forEach(q=>{if(!groups.has(q._key))groups.set(q._key,[]);groups.get(q._key).push(q);});
 const keys=shuffle([...groups.keys()]),out=[];
 while(out.length<n){let added=false;for(const key of keys){if(groups.get(key).length&&out.length<n){out.push(groups.get(key).pop());added=true;}}if(!added)break;}
 return out;
}
function flatten(subject,s,selected=null) {
 return Object.entries(subject.units).flatMap(([u,unit])=>Object.entries(unit.topics).flatMap(([t,topic])=>selected&&!selected.includes(`${u}/${t}`)?[]:topic.questions.map(q=>({...q,_key:`${s}/${u}/${t}`,_source:`${unit.code} · ${topic.title}`}))));
}
function topicFields(subject) {
 return Object.entries(subject.units).map(([u,unit])=>`<fieldset><legend>${esc(unit.code+' · '+unit.title)}</legend>${notice(unit.notice)}${Object.entries(unit.topics).map(([t,topic])=>`<label class="topic-choice"><input type="checkbox" name="topics" value="${esc(u+'/'+t)}" checked> ${esc(topic.title)} <small>${topic.questions.length} questions</small></label>`).join('')}</fieldset>`).join('');
}
function renderHome(bank) {
 const labels={'ocr-aaq-it-da':['IT: Data Analytics','01','Data, decisions and machine learning.'],'ocr-a-cs-h446':['Computer Science','02','Computer systems, networks and software.'],'ocr-aaq-engineering':['Engineering','03','Materials, manufacturing and sustainable design.']};
 app.innerHTML=title('The learning never stops','Choose your subject. Start revising.','Free revision, one question at a time. Explore units and practise with multiple choice or written answers — no account required.')+
 `<p class="notice">Lite keeps learning simple. Your answers and current session score disappear when you leave or reload; there are no accounts, XP or saved progress.</p><div class="grid subject-grid">${Object.entries(bank).map(([s,subject])=>{const label=labels[s]||[subject.subtitle,'学',subject.title];return `<a class="card subject-card" href="${esc(url({page:'subject',s}))}"><span class="subject-number">${label[1]}</span><p class="eyebrow">${esc(subject.subtitle)}</p><h2>${esc(label[0])}</h2><p>${esc(label[2])}</p><div class="meta"><span>${Object.keys(subject.units).length} units · ${Object.values(subject.units).reduce((n,u)=>n+questionCount(u),0)} questions</span><strong>Explore →</strong></div></a>`;}).join('')}</div><section class="mission"><p class="eyebrow">Everyone belongs in the dojo</p><h2>Education shouldn't come with a paywall.</h2><p>TechDojo Lite gives you access to revision questions without an account. Visit <a href="https://techdojo.findmycode.org/">TechDojo Full</a> for accounts, XP, companions and saved progress.</p></section>`;
}
function renderSubject(subject,s) {
 app.innerHTML=title('Choose a unit',subject.subtitle,subject.title)+`<div class="actions">${button('Train across this course →',{page:'training',s})}${button('Build a practice paper',{page:'exam',s})}${s==='ocr-a-cs-h446'?button('Unlimited binary maths',{page:'maths'}):''}</div><div class="grid">${Object.entries(subject.units).map(([u,unit])=>`<a class="card" href="${esc(url({page:'unit',s,u}))}"><span class="code">${esc(unit.code)}</span><h2>${esc(unit.title)}</h2><p>${Object.keys(unit.topics).length} topic areas · ${questionCount(unit)} questions</p>${unit.notice?`<p class="unit-notice">${esc(unit.notice)}</p>`:''}<strong>View topics →</strong></a>`).join('')}</div>`;
}
function renderUnit(subject,s,u) {
 const unit=subject.units[u];if(!unit)throw Error('That unit was not found.');
 const groups=new Map();Object.entries(unit.topics).forEach(([t,topic])=>{const group=topic.group||'';if(!groups.has(group))groups.set(group,[]);groups.get(group).push([t,topic]);});
 app.innerHTML=`<p class="crumbs"><a href="index.html">Subjects</a> / <a href="${esc(url({page:'subject',s}))}">${esc(subject.subtitle)}</a></p>`+title(unit.code,unit.title,'Choose a topic area to start training.')+notice(unit.notice)+(s==='ocr-a-cs-h446'?`<div class="actions">${button('1.4.1 · Unlimited binary maths',{page:'maths'})}</div>`:'')+[...groups.entries()].map(([group,topics])=>`${group?`<h2>${esc(group)}</h2>`:''}<div class="grid">${topics.map(([t,topic])=>{const counts={mcq:0,short:0,long:0};topic.questions.forEach(q=>counts[q.t]++);return `<a class="card" href="${esc(url({page:'quiz',s,u,t}))}"><h3>${esc(topic.title)}</h3><p>${esc(topic.blurb)}</p><p class="counts">${counts.mcq} multiple choice · ${counts.short} short · ${counts.long} extended</p><div class="meta"><span>${topic.questions.length} questions</span><strong>Start training →</strong></div></a>`;}).join('')}</div>`).join('')+notice(unit.coming);
}
function renderTraining(subject,s) {
 app.innerHTML=title('Bring it all together','Train across your course.','Choose topics, then choose Quick Fire, written answers or a mixed paper.')+`<form class="training-form" id="training-form"><div class="actions"><button class="btn ghost" type="button" id="select-all">Select all</button><button class="btn ghost" type="button" id="select-none">Clear topics</button></div>${topicFields(subject)}<p id="selection-error" class="error" role="alert"></p><button class="btn">Choose my training →</button></form>`;
 bindSelection();document.getElementById('training-form').onsubmit=e=>{e.preventDefault();const selected=selections();if(!selected.length){document.getElementById('selection-error').textContent='Select at least one topic.';return;}renderQuiz(flatten(subject,s,selected),'Course training',url({page:'training',s}),{course:true});};
}
function selections(){return [...app.querySelectorAll('input[name="topics"]:checked')].map(el=>el.value);}
function bindSelection(onChange=()=>{}) {for(const [id,checked] of [['select-all',true],['select-none',false]])document.getElementById(id).onclick=()=>{app.querySelectorAll('input[name="topics"]').forEach(el=>el.checked=checked);onChange();};}
function renderQuiz(questions,heading,back,{course=false,paper=false,minutes=0}={}) {
 if(!questions.length)throw Error('No questions are available for that selection.');
 window.QUESTIONS=questions;
 app.innerHTML=`<p class="crumbs"><a href="${esc(back)}">← Back to topics</a></p><p class="muted">Current session only. No answers or scores are saved.</p><div id="quiz-data" data-course="${course?'1':'0'}" data-paper="${paper?'1':'0'}" data-minutes="${minutes}" hidden></div><section id="modes" class="modes" hidden><p class="eyebrow">Choose your training</p><h2 class="modes-title">${esc(heading)}</h2><p class="lead">Written answers use approximate keyword marking. Check the mark scheme and adjust the ticks yourself. These are independent practice questions, not official OCR assessments.</p><div id="mode-list" class="mode-list"></div></section>${paper?'<p id="exam-timer" role="status"></p><p class="notice">The timer is advisory. Online practice gives instant feedback; use the blank printable paper for exam conditions.</p>':''}<section id="quiz" class="quiz" hidden><div class="bar"><div id="progress"></div></div><div class="status"><span id="count"></span><span id="mode-label" class="mode-label"></span><span id="score"></span></div><p id="question-source" class="muted"></p><p id="qtag" class="qtag"></p><h2 id="question"></h2><div id="options" class="options"></div><div id="written" class="written" hidden><label for="answer" class="sr-only">Your answer</label><textarea id="answer" rows="8" placeholder="Type your answer here…" spellcheck="true"></textarea><div class="wmeta"><span id="wcount">0 words</span><span id="whint"></span></div><div class="actions"><button id="mark" class="btn" type="button">Mark my answer</button><button id="skip" class="btn ghost" type="button">Show mark scheme</button></div><div id="scheme" class="scheme" aria-live="polite" hidden></div></div><div id="feedback" class="feedback" role="status" hidden></div><div class="actions"><button id="next" class="btn" hidden>Next question →</button></div></section><section id="result" class="result" hidden><p id="result-mode" class="eyebrow"></p><h2 id="result-score"></h2><p id="result-msg" class="lead"></p><div id="topic-breakdown"></div><div id="breakdown" class="breakdown"></div><div id="revise" class="revise"></div><div class="actions"><button id="retry" class="btn">Try again</button><button id="export-pdf" class="btn ghost" type="button">Export answers &amp; mark schemes (PDF)</button><button id="change-mode" class="btn ghost" type="button">Choose another mode</button><a class="btn ghost" href="${esc(back)}">Back to topics</a></div></section><div id="print-sheet" class="print-sheet" aria-hidden="true"></div>`;
 const script=document.createElement('script');script.src='quiz.js';script.onerror=()=>{app.textContent='Could not load the trainer. Reload to try again.';};app.appendChild(script);document.title=heading+' · TechDojo Lite';window.scrollTo(0,0);
}
function renderMaths() {
 app.innerHTML=title('Computer Science · 1.4.1','Binary maths lab.','Fresh numbers every round. Calculate your answer, check the working and try again.')+notice('Floating-point exercises use an 8-bit two’s complement mantissa with the binary point after the sign bit, and a 4-bit two’s complement exponent. Answers are calculated in your browser.')+`<label for="math-type">Exercise</label><select id="math-type"><option value="mixed">Mix all skills</option>${Object.entries(TDMath.types).map(([type,label])=>`<option value="${type}">${esc(label)}</option>`).join('')}</select><h2 id="math-question"></h2><form id="math-form" class="math-form"><label for="math-answer">Your answer</label><input id="math-answer" autocomplete="off" required maxlength="100"><button class="btn" id="math-check">Check answer</button></form><div id="math-feedback" role="status" class="notice" hidden></div><button id="math-next" class="btn" hidden>New question →</button><div class="actions">${button('Back to CS topics',{page:'unit',s:'ocr-a-cs-h446',u:'h446-01'})}</div>`;
 const $=id=>document.getElementById(id);let q,done;
 function next(){const type=$('math-type').value,previous=q;do{const seed=crypto.getRandomValues(new Uint32Array(1))[0];q=TDMath.generate(type==='mixed'?shuffle(Object.keys(TDMath.types))[0]:type,seed);}while(previous&&previous.q===q.q);done=false;$('math-question').textContent=q.q;$('math-answer').value='';$('math-answer').readOnly=false;$('math-check').disabled=false;$('math-feedback').hidden=true;$('math-next').hidden=true;}
 $('math-form').onsubmit=e=>{e.preventDefault();if(done)return;done=true;const ok=TDMath.check(q,$('math-answer').value);$('math-answer').readOnly=true;$('math-check').disabled=true;$('math-feedback').hidden=false;$('math-feedback').textContent=(ok?'Correct! ':'Keep practising. ')+`Answer: ${q.answer}. ${q.why}`;$('math-next').hidden=false;$('math-next').focus();};$('math-next').onclick=()=>{next();$('math-answer').focus();};$('math-type').onchange=next;next();
}
function renderExam(subject,s) {
 const names={mcq:'Multiple choice',short:'Short answers',long:'Extended response'};
 const pool=flatten(subject,s);const defaults={mcq:Math.min(10,pool.filter(q=>q.t==='mcq').length),short:Math.min(3,pool.filter(q=>q.t==='short').length),long:Math.min(1,pool.filter(q=>q.t==='long').length)};
 app.innerHTML=title('Your own practice paper','Build an exam.','Choose topics and question counts. Print a blank paper and a separate mark scheme, or practise the same questions online.')+notice('Independent revision papers, not official OCR papers. Generated maths is a separate lab. Papers remain here only until you leave or reload this page.')+`<form class="training-form" id="exam-form"><fieldset><legend>Paper settings</legend><div class="exam-counts">${Object.entries(names).map(([type,name])=>`<label>${name}<input type="number" name="${type}" min="0" max="100" value="${defaults[type]}" required><small id="available-${type}"></small></label>`).join('')}<label>Time in minutes<input name="minutes" type="number" min="0" max="240" value="30" required><small>0 = untimed; online timing is advisory.</small></label></div></fieldset><div class="actions"><button class="btn ghost" type="button" id="select-all">Select all topics</button><button class="btn ghost" type="button" id="select-none">Clear topics</button></div>${topicFields(subject)}<p id="exam-error" class="error" role="alert"></p><button class="btn">Generate my paper →</button></form>`;
 const form=document.getElementById('exam-form');
 function available(){const pool=flatten(subject,s,selections());for(const type of Object.keys(names))document.getElementById('available-'+type).textContent=pool.filter(q=>q.t===type).length+' available in current selection';}
 bindSelection(available);form.addEventListener('change',available);available();
 form.onsubmit=e=>{e.preventDefault();const selected=selections(),error=document.getElementById('exam-error');if(!selected.length){error.textContent='Select at least one topic.';return;}
 const counts=Object.fromEntries(Object.keys(names).map(t=>[t,Number(form.elements[t].value)]));const total=Object.values(counts).reduce((a,b)=>a+b,0),minutes=Number(form.elements.minutes.value);
 if(Object.values(counts).some(n=>!Number.isInteger(n)||n<0||n>100)||total<1||total>150||!Number.isInteger(minutes)||minutes<0||minutes>240){error.textContent='Choose 1–150 questions in total (up to 100 per type) and 0–240 minutes.';return;}
 const pool=flatten(subject,s,selected),questions=[];for(const type of Object.keys(names)){const typed=pool.filter(q=>q.t===type);if(counts[type]>typed.length){error.textContent=`Only ${typed.length} ${names[type].toLowerCase()} are available. Reduce the count or select more topics.`;return;}questions.push(...balanced(typed,counts[type]));}
 renderPaper({questions,title:subject.subtitle,minutes,s});};
}
function renderPaper(paper,answers=false) {
 const marks=paper.questions.reduce((n,q)=>n+(q.t==='mcq'?1:q.marks),0);
 app.innerHTML=`<section class="paper-controls"><div class="actions"><button class="btn" id="practice-paper">Practise this paper online</button><button class="btn ghost" id="toggle-scheme">${answers?'Blank question paper':'Separate mark scheme'}</button><button class="btn ghost" id="print-paper">Print / Save as PDF</button>${button('Build another paper',{page:'exam',s:paper.s})}</div>${notice('Browser print dialog → Save as PDF. Online practice gives feedback after each question; written marks are self-assessed.')}</section><article class="exam-paper"><h1>TechDojo Lite · ${answers?'Mark scheme':'Practice paper'}</h1><h2>${esc(paper.title)}</h2><p>${paper.questions.length} questions · ${marks} marks · ${paper.minutes?paper.minutes+' minutes':'Untimed'}</p><p>Independent revision questions. Written marking is indicative; use judgement and the specification.</p>${answers?'':'<p>Name: __________________________________ Date: __________________</p>'}${paper.questions.map((q,i)=>`<section class="paper-question"><p class="muted">${esc(q._source)}</p><h3>${i+1}. ${esc(q.q)} <small>[${q.t==='mcq'?1:q.marks} marks]</small></h3>${q.t==='mcq'?(answers?`<p><strong>Answer: ${String.fromCharCode(65+q.a)} · ${esc(q.o[q.a])}</strong></p><p>${esc(q.e)}</p>`:`<ol type="A">${q.o.map(o=>`<li>${esc(o)}</li>`).join('')}</ol><p>Answer: ______</p>`):(answers?`<p>Credit up to ${q.marks} marks using these points:</p><ul>${q.pts.map(pt=>`<li>${esc(pt.p)}</li>`).join('')}</ul><p><strong>Example answer:</strong> ${esc(q.model)}</p>${q.t==='long'?'<p>Credit relevant detail, accuracy and developed explanation. Keyword matches alone do not establish an exam level.</p>':''}`:`<div class="answer-space" style="min-height:${q.t==='long'?220:100}px"></div>`)}</section>`).join('')}</article>`;
 document.getElementById('toggle-scheme').onclick=()=>renderPaper(paper,!answers);document.getElementById('practice-paper').onclick=()=>renderQuiz(paper.questions,'Custom practice paper',url({page:'exam',s:paper.s}),{paper:true,minutes:paper.minutes});
 document.getElementById('print-paper').onclick=()=>{document.body.classList.add('paper-print');window.addEventListener('afterprint',()=>document.body.classList.remove('paper-print'),{once:true});window.print();};window.scrollTo(0,0);
}
async function boot(){try{
 const page=params.get('page')||'home';if(page==='maths'){renderMaths();return;}
 const response=await fetch('data/bank.json');if(!response.ok)throw Error('Could not load the question bank. Reload to try again.');const bank=await response.json();
 if(page==='home'){renderHome(bank);return;}const s=params.get('s'),subject=bank[s];if(!subject)throw Error('That subject was not found.');
 document.title=subject.subtitle+' · TechDojo Lite';
 if(page==='subject')renderSubject(subject,s);else if(page==='unit')renderUnit(subject,s,params.get('u'));else if(page==='training')renderTraining(subject,s);else if(page==='exam')renderExam(subject,s);else if(page==='quiz'){const u=params.get('u'),t=params.get('t'),topic=subject.units[u]?.topics[t];if(!topic)throw Error('That topic was not found.');renderQuiz(flatten(subject,s,[u+'/'+t]),topic.title,url({page:'unit',s,u}));}else throw Error('That page was not found.');
 }catch(error){app.innerHTML=`<h1>Revision unavailable</h1><p role="alert">${esc(error.message)}</p><a class="btn" href="index.html">Back to subjects</a>`;}}
boot();
