/* Deterministic arithmetic generator. OCR-style 8-bit mantissa / 4-bit exponent.
   Integer arithmetic is used for floating representations to avoid rounding drift. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.TDMath=factory();})(typeof self!=='undefined'?self:this,function(){
 const types={binary_encode:'Denary → binary',binary_decode:'Binary → denary',hex_encode:'Denary → hexadecimal',hex_decode:'Hexadecimal → denary',binary_hex:'Binary → hexadecimal',hex_binary:'Hexadecimal → binary',signed_add:'Signed binary addition',signed_sub:'Signed binary subtraction',signmag_decode:'Decode sign and magnitude',twos_encode:'Negative two’s complement',twos_decode:'Decode two’s complement',signmag_encode:'Sign and magnitude',add:'Binary addition',subtract:'Binary subtraction',shift:'Logical shifts',and:'AND masks',or:'OR masks',xor:'XOR masks',fixed:'Fixed-point interpretation',float_decode:'Decode floating point',float_normalize:'Normalise floating point',float_add:'Floating-point addition',float_sub:'Floating-point subtraction'};
 function bits(n,w=8){return ((n%2**w+2**w)%2**w).toString(2).padStart(w,'0');}
 function generate(type,seed){let state=seed>>>0;function r(n){state=(Math.imul(state,1664525)+1013904223)>>>0;return (state>>>8)%n;}const a=r(256),b=r(256),sign=r(2)?-1:1;let q,answer,why;
 switch(type){
 case 'binary_encode':q=`Write ${a} as an unsigned 8-bit binary integer.`;answer=bits(a);why='Use weights 128, 64, 32, 16, 8, 4, 2, 1.';break;
 case 'binary_decode':q=`Convert unsigned binary ${bits(a)} to denary.`;answer=String(a);why='Add the place values whose bits are 1.';break;
 case 'hex_encode':q=`Convert denary ${a} to two hexadecimal digits.`;answer=a.toString(16).toUpperCase().padStart(2,'0');why='Divide into two base-16 digits; A–F represent 10–15.';break;
 case 'hex_decode':q=`Convert hexadecimal ${a.toString(16).toUpperCase().padStart(2,'0')} to denary.`;answer=String(a);why=`High digit × 16 + low digit = ${a}.`;break;
 case 'binary_hex':q=`Convert unsigned binary ${bits(a)} to two hexadecimal digits.`;answer=a.toString(16).toUpperCase().padStart(2,'0');why='Split the byte into two four-bit nibbles and convert each nibble to a hex digit.';break;
 case 'hex_binary':q=`Convert hexadecimal ${a.toString(16).toUpperCase().padStart(2,'0')} to eight binary bits.`;answer=bits(a);why='Convert each hex digit to four binary bits and concatenate.';break;
 case 'signmag_decode':{let n=(a&128)?-(a&127):(a&127);q=`Interpret ${bits(a)} as 8-bit sign and magnitude. Give denary.`;answer=String(n);why='The first bit gives the sign; the remaining seven bits give the magnitude. Both zero representations mean zero.';break;}
 case 'signed_add':case 'signed_sub':{let x=a%128-64,y=b%128-64,n=type==='signed_add'?x+y:x-y;q=`${type==='signed_add'?'Add':'Subtract the second from the first'} ${bits(x)} and ${bits(y)}, both 8-bit two’s complement integers. Give the 8-bit two’s complement result.`;answer=bits(n);why=`The signed values are ${x} and ${y}: ${x} ${type==='signed_add'?'+':'−'} ${y} = ${n}. These operands are chosen to avoid overflow.`;break;}
 case 'twos_encode':{let n=-(a%127+1);q=`Write ${n} in 8-bit two’s complement.`;answer=bits(n);why=`For a negative integer use 256 + (${n}), then write the 8 bits.`;break;}
 case 'twos_decode':{let n=a>=128?a-256:a;q=`Interpret ${bits(a)} as an 8-bit two’s complement integer.`;answer=String(n);why='The first bit has weight −128; the remaining weights are 64 down to 1.';break;}
 case 'signmag_encode':{let n=-(a%127+1);q=`Write ${n} as 8-bit sign and magnitude.`;answer='1'+bits(-n,7);why='The leading 1 is the negative sign; the other seven bits hold the magnitude.';break;}
 case 'add':{let x=a%128,y=b%128;q=`Add unsigned ${bits(x)} and ${bits(y)}. Give an 8-bit result.`;answer=bits(x+y);why=`${x} + ${y} = ${x+y}; carry 1 when a column totals 2 or 3.`;break;}
 case 'subtract':{let x=Math.max(a,b),y=Math.min(a,b);q=`Subtract unsigned ${bits(y)} from ${bits(x)}. Give an 8-bit result.`;answer=bits(x-y);why=`${x} − ${y} = ${x-y}. Borrow across columns or add the subtrahend’s two’s complement.`;break;}
 case 'shift':{let n=b%3+1,left=b%2===0;q=`Logical ${left?'left':'right'} shift ${bits(a)} by ${n} positions, retaining 8 bits and discarding shifted-out bits.`;answer=bits(left?(a<<n)&255:a>>>n);why='Fill vacated positions with 0. A left shift can lose high bits; a right shift loses low bits.';break;}
 case 'and':case 'or':case 'xor':{let val=type==='and'?a&b:type==='or'?a|b:a^b;q=`Apply bitwise ${type.toUpperCase()} to ${bits(a)} and ${bits(b)}.`;answer=bits(val);why=type==='and'?'AND is 1 only when both input bits are 1.':type==='or'?'OR is 1 when at least one input bit is 1.':'XOR is 1 when the input bits differ.';break;}
 case 'fixed':{let m=a>=128?a-256:a;q=`Interpret ${bits(a)} as signed two’s complement fixed point with four fractional bits (divide its signed integer value by 16). Give denary.`;answer=String(m/16);why=`Signed integer ${m} ÷ 16 = ${answer}.`;break;}
 case 'float_decode':{let m=sign*(64+a%64);if(m>127)m=127;let e=b%9-4;q=`Decode floating point: mantissa ${bits(m)} (8-bit two’s complement fraction, binary point after the sign bit), exponent ${bits(e,4)} (4-bit two’s complement). Give denary.`;answer=String(m/128*2**e);why=`Mantissa ${m}/128 × 2^${e} = ${answer}.`;break;}
 case 'float_normalize':{let m=sign*(17+a%15),e=b%4+2;let norm=m,exp=e;while(norm>=0?norm<64:norm>=-64){norm*=2;exp--;}q=`Normalise mantissa ${bits(m)} and exponent ${bits(e,4)}. Both use two’s complement; mantissa point is after the sign bit. Answer: 8 mantissa bits, space, 4 exponent bits.`;answer=bits(norm)+' '+bits(exp,4);why='Shift the mantissa left and decrease the exponent equally. Normalised positive mantissas begin 01; negative ones begin 10.';break;}
 case 'float_add':case 'float_sub':{let m1=(16+a%8*4)*sign,m2=16+b%8*4,e1=r(4)+1,e2=r(4)+1,val1=m1/128*2**e1,val2=m2/128*2**e2,result=type==='float_add'?val1+val2:val1-val2;q=`${type==='float_add'?'Add':'Subtract the second from the first'} these floating-point numbers: ${bits(m1)} ${bits(e1,4)} and ${bits(m2)} ${bits(e2,4)}. Mantissas are 8-bit two’s complement fractions; exponents are 4-bit two’s complement. Give the denary result.`;answer=String(result);let common=Math.max(e1,e2);why=`Align to exponent ${common}: shift the mantissa of the smaller exponent right by the exponent difference (retain all fractional bits in your working). The values are ${val1} and ${val2}, so ${val1} ${type==='float_add'?'+':'−'} ${val2} = ${answer}.`;break;}
 default:throw Error('Unknown exercise');}
 return {type,seed,q,answer,why};
 }
 function check(question,input){const s=String(input).trim();if(['binary_decode','hex_decode','twos_decode','signmag_decode','fixed','float_decode','float_add','float_sub'].includes(question.type))return s!=='' && /^[-+]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s) && Number(s)===Number(question.answer);return s.toUpperCase().replace(/\s/g,'')===question.answer.replace(/\s/g,'');}
 return {types,generate,check,bits};
});
